name: GraalVM Linux build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector:v0.5.1
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: admin
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
    permissions: # The permissions the surefire test report
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Versions
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java --version

      - name: Build
        env:
          SERVER_ENV: DEV
          SERVER_PORT: 9999
          SPRING_FLYWAY_URL: jdbc:postgresql://localhost:5432/app_db
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/app_db
        run: mvn clean package -Dslogback.logstash.enabled=false -ntp -Dslogback.logstash.enabled=false

      - uses: scacap/action-surefire-report@v1
        if: success() || failure()
        # if: github.ref != 'refs/heads/master'
        with:
          check_name: Surefire test report
          report_paths: '**/surefire-reports/*.xml'

      - name: File system info
        run: |
          echo "===========> github.workspace var: ${{ github.workspace }}"
          echo "===========> pwd:"
          pwd
          echo "===========> ls -hal:"
          ls -hal
          echo "===========> ls -hal /src:"
          ls -hal ./src
          echo "===========> ls -hal /target:"
          ls -hal ./target

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: kbalazsworks/semantic_log_classifier_api:${{ env.RELEASE_VERSION }}, kbalazsworks/semantic_log_classifier_api:latest, kbalazsworks/semantic_log_classifier_api:commit_sha_short_${{ env.COMMIT_SHA_SHORT }}
