name: GraalVM Linux build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # The permissions the surefire test report
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Versions
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java --version

      - name: Build
        env:
          SERVER_ENV: DEV
          SERVER_PORT: 9999
        run: mvn clean compile -DskipTests -Dslogback.logstash.enabled=false

      - uses: scacap/action-surefire-report@v1
        if: success() || failure()
        # if: github.ref != 'refs/heads/master'
        with:
          check_name: Surefire test report
          report_paths: '**/surefire-reports/*.xml'

      - name: File system info
        run: |
          echo "===========> github.workspace var: ${{ github.workspace }}"
          echo "===========> pwd:"
          pwd
          echo "===========> ls -hal:"
          ls -hal
          echo "===========> ls -hal /src:"
          ls -hal ./src
          echo "===========> ls -hal /target:"
          ls -hal ./target
